name: reviewdog

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          fail_level: warning